esphome:
  name: starlamp

esp32:
  board: upesy_wroom
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Starlamp Fallback Hotspot"
    password: "0gg0hRUvSK0N"

captive_portal:
    